//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT_Hotelaria.Message {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ACT_Hotelaria.Message.ResourceMessages", typeof(ResourceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ErroInesperado {
            get {
                return ResourceManager.GetString("ErroInesperado", resourceCulture);
            }
        }
        
        public static string NomeObrigatorio {
            get {
                return ResourceManager.GetString("NomeObrigatorio", resourceCulture);
            }
        }
        
        public static string EmailObrigatorio {
            get {
                return ResourceManager.GetString("EmailObrigatorio", resourceCulture);
            }
        }
        
        public static string TelefoneObrigatorio {
            get {
                return ResourceManager.GetString("TelefoneObrigatorio", resourceCulture);
            }
        }
        
        public static string ClienteObrigatorio {
            get {
                return ResourceManager.GetString("ClienteObrigatorio", resourceCulture);
            }
        }
        
        public static string CheckinObrigatorio {
            get {
                return ResourceManager.GetString("CheckinObrigatorio", resourceCulture);
            }
        }
        
        public static string CheckoutObrigatorio {
            get {
                return ResourceManager.GetString("CheckoutObrigatorio", resourceCulture);
            }
        }
        
        public static string CheckinAndCheckoutDiferente {
            get {
                return ResourceManager.GetString("CheckinAndCheckoutDiferente", resourceCulture);
            }
        }
        
        public static string DependenteJaCadastrado {
            get {
                return ResourceManager.GetString("DependenteJaCadastrado", resourceCulture);
            }
        }
        
        public static string ReservaJaCadastrada {
            get {
                return ResourceManager.GetString("ReservaJaCadastrada", resourceCulture);
            }
        }
        
        public static string ClienteNaoEncontrado {
            get {
                return ResourceManager.GetString("ClienteNaoEncontrado", resourceCulture);
            }
        }
        
        public static string CPFJaCadastrado {
            get {
                return ResourceManager.GetString("CPFJaCadastrado", resourceCulture);
            }
        }
        
        public static string PreenchimentoDependenteObrigatorio {
            get {
                return ResourceManager.GetString("PreenchimentoDependenteObrigatorio", resourceCulture);
            }
        }
        
        public static string CPFObrigatorio {
            get {
                return ResourceManager.GetString("CPFObrigatorio", resourceCulture);
            }
        }
        
        public static string PrecoMaiorQueZero {
            get {
                return ResourceManager.GetString("PrecoMaiorQueZero", resourceCulture);
            }
        }
        
        public static string TelefoneNumero {
            get {
                return ResourceManager.GetString("TelefoneNumero", resourceCulture);
            }
        }
        
        public static string ReservaNaoEncontrada {
            get {
                return ResourceManager.GetString("ReservaNaoEncontrada", resourceCulture);
            }
        }
    }
}
